# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flexbox Fun
email: mwalker@chef.io
description: > # this means to ignore newlines until "baseurl:"
  A playground for research in flexbox, the picture element, and responsive web design goodies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: magwalk
github_username:  magwalk
exclude: [‘css’, ‘_scss’]
keep_files: ['_site/css']

# Build settings
markdown: kramdown
